### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by yxeri** [urtzurd/html-audio#1]
There is no license attached to this project. Is this intentional? 

I would love to be able to use your code as the base of a personal project of mine and push back improvements. What I'm planning to do is use a Android phone to modulate my voice during a LARP and would like to create a fork and make some visual changes and add support for Firefox.

**Comment by urtzurd** [comment]
Hi!

Thanks for the interest on the project! I didn't add it because It was a simple proof of concept to play around with the new (back then) HTML5 audio capabilities. I added a MIT license to it, so feel free to fork and modify it as you wish, as long as you provide attribution back to me.

Cheers!
